plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'app.pie.recorder'
    compileSdk 35

    def ciRunNumber = System.getenv('GITHUB_RUN_NUMBER')
    def buildNumber = ciRunNumber ? ciRunNumber.toInteger() : 1

    defaultConfig {
        applicationId 'app.pie.recorder'
        minSdk 29
        targetSdk 35
        versionCode buildNumber
        versionName "0.1.${buildNumber}"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
