import OpenAI from 'openai';
import { NextResponse } from 'next/server';
import { currentUser } from '@clerk/nextjs/server';
import { rateLimit, readJsonObject, safeClientError, textField } from '../../security';
import { resolvePieUserId } from '../../usageEntitlements';
import { getPieContextSnapshot } from '../../pieContext';

const stageContext: Record<number,string>={1:'Raw Talent: experimenting, creating songs, and learning a repeatable creative workflow.',2:'Hot Prospect: preparing a real release with ownership, calendar, assets, and a clear plan.',3:'Talent Show Boss: prelaunch audience building, content, fan capture, media, video, and merch prep.',4:'Local Hero: launch execution, distribution, outreach, release-day coordination, and local momentum.',5:'Regional Hit: sustained campaigns, analytics, business discipline, accounting, and profitable repeatable promotion.',6:'National Hitmaker: gigs, touring, live revenue, booking, band operations, travel, and market expansion.',7:'International Rock Star: scaling from local/regional success into national markets with a team and repeatable operations.',8:'World Legend: international campaigns, touring, rights, partnerships, and market-by-market global operations.'};
const stageNames=['','Raw Talent','Hot Prospect','Talent Show Boss','Local Hero','Regional Hit','National Hitmaker','International Rock Star','World Legend'];
function fallback(level:number,context:any){const next=Math.min(8,level+1);const score=context?.score?.current??0;return `Focus on the next measurable outcome for Stage ${level}.\n\n1. Finish the single highest-priority task that moves the current release or business objective forward.\n2. Close the weakest Pie Score dimension before adding more activity. Your current score is ${score}/1000.\n3. Review what is required to reach Stage ${next} and close the biggest gap first.\n\nUse Data, Marketing, Calendar, Gigs, Business, Accounting, Legal, and Live Support when the next step requires contacts, promotion, scheduling, revenue, rights, or professional help.`;}
async function serverStage(){const user=await currentUser().catch(()=>null);if(!user)return {level:1,name:stageNames[1]};const p=(user.publicMetadata||{}) as Record<string,unknown>;const u=(user.unsafeMetadata||{}) as Record<string,unknown>;const hasProfile=Boolean(p.pieOnboardingCompleted||p.piePlanLevel||u.pieOnboardingStartedAt||u.pieOnboardingCompleted);if(!hasProfile)return {level:8,name:stageNames[8]};const status=String(p.pieSubscriptionStatus||'free').toLowerCase();const inactive=['past_due','canceled','cancelled','unpaid','incomplete_expired'].includes(status);const level=inactive?1:Math.max(1,Math.min(8,Number(p.piePlanLevel||1)));return {level,name:stageNames[level]||`Stage ${level}`};}

export async function POST(req:Request){const limited=rateLimit(req,'pie-guide',20,60_000);if(limited)return limited;try{const userId=await resolvePieUserId();if(!userId)return NextResponse.json({error:'Sign in to use Pie Guide.'},{status:401});const body=await readJsonObject(req,16_000);const question=textField(body.question,5_000);if(!question)return NextResponse.json({error:'Ask the Pie Guide a question.'},{status:400});const [{level,name},context]=await Promise.all([serverStage(),getPieContextSnapshot()]);if(!process.env.OPENAI_API_KEY)return NextResponse.json({answer:fallback(level,context),contextUsed:Boolean(context)});
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const compactContext=JSON.stringify(context||{}).slice(0,7000);const response=await client.responses.create({model:process.env.OPENAI_TEXT_MODEL||'gpt-5.6',max_output_tokens:1300,input:[{role:'system',content:`You are Pie Guide, the user's AI artist manager inside Pie. The server-verified business stage is ${level}: ${name}. ${stageContext[level]||''}\n\nCurrent Pie operating snapshot: ${compactContext}\n\nUse this snapshot to identify the biggest verified gaps. Prioritize 3-5 concrete next actions, in order. Distinguish between activity and outcomes: do not reward busywork. Prefer actions that improve completion, quality, determination, connections, or execution and explain which Pie Score dimension each action helps. Point to relevant Pie areas such as Music, Songs, Scoreboard, Video, Marketing, Data, Merch, Gigs, Calendar, Travel, Business, Accounting, Licensing, Legal, Band, Contract Studio, or Live Support. Never invent data that is not in the snapshot. Do not pretend to be a lawyer, accountant, booking agent, or tax professional; route consequential legal/tax matters through Live Support to qualified professionals. Do not promise guaranteed success, chart placement, or industry access. Keep guidance concise and operational.`},{role:'user',content:question}]});return NextResponse.json({answer:response.output_text.trim()||fallback(level,context),contextUsed:Boolean(context),stage:{level,name}},{headers:{'Cache-Control':'no-store'}});}catch(error){return NextResponse.json({error:safeClientError(error,'Pie Guide failed.')},{status:400});}}
