'use client';

import { useEffect, useMemo, useState } from 'react';
import { complianceFrameworks as frameworks, complianceStatusLabels as statusLabels, reusableSecurityCore, type ComplianceFramework, type ComplianceStatus } from '../lib/complianceCatalog';

type EventRow={id:string;source:string;event_type:string;severity:string;status:string;title:string;summary?:string;critical_count:number;high_count:number;medium_count:number;low_count:number;workflow?:string;observed_at:string;resolved_at?:string;metadata?:Record<string,unknown>};
type WorkflowRun={id:string;name:string;status:string;conclusion:string;event:string;headSha:string;branch:string;createdAt:string;updatedAt:string;htmlUrl:string};

export default function CyberSecurityWorkspace(){
  const [events,setEvents]=useState<EventRow[]>([]);const [runs,setRuns]=useState<WorkflowRun[]>([]);const [settings,setSettings]=useState<any>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  const [draftStatus,setDraftStatus]=useState<Record<string,ComplianceStatus>>({});const [notes,setNotes]=useState<Record<string,string>>({});
  async function load(){setBusy(true);setStatus('');try{const r=await fetch('/api/security',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load Cyber Security.');setEvents(Array.isArray(d.events)?d.events:[]);setRuns(Array.isArray(d.workflowRuns)?d.workflowRuns:[]);setSettings(d.settings||null);}catch(e){setStatus(e instanceof Error?e.message:'Could not load Cyber Security.');}finally{setBusy(false);}}
  useEffect(()=>{load();},[]);
  const stats=useMemo(()=>{const open=events.filter(e=>e.status!=='resolved');return{critical:open.filter(e=>e.severity==='critical').length,high:open.filter(e=>e.severity==='high').length,medium:open.filter(e=>e.severity==='medium').length,total:events.length,failedRuns:runs.filter(r=>r.conclusion==='failure').length};},[events,runs]);
  const latestCompliance=useMemo(()=>{const result:Record<string,{status:ComplianceStatus;note:string;at:string}>={};for(const event of [...events].sort((a,b)=>new Date(b.observed_at).getTime()-new Date(a.observed_at).getTime())){if(event.event_type!=='compliance_checkpoint'||event.source!=='pie-compliance')continue;const id=String(event.metadata?.frameworkId||'');const eventStatus=String(event.metadata?.status||'') as ComplianceStatus;if(id&&!result[id]&&statusLabels[eventStatus])result[id]={status:eventStatus,note:String(event.metadata?.note||event.summary||''),at:event.observed_at};}return result;},[events]);
  async function resolve(id:string){setBusy(true);try{const r=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'resolve',id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not resolve event.');await load();}catch(e){setStatus(e instanceof Error?e.message:'Could not resolve event.');}finally{setBusy(false);}}
  async function logCompliance(item:ComplianceFramework){const next=draftStatus[item.id]||latestCompliance[item.id]?.status||item.defaultStatus;setBusy(true);setStatus('');try{const r=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'recordCompliance',frameworkId:item.id,framework:item.name,status:next,note:notes[item.id]||''})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not log compliance checkpoint.');setNotes(current=>({...current,[item.id]:''}));setStatus(`${item.name} checkpoint logged.`);await load();}catch(e){setStatus(e instanceof Error?e.message:'Could not log compliance checkpoint.');}finally{setBusy(false);}}
  return <main className="growthWorkspace">
    <section className="hero"><p className="eyebrow">Security Operations</p><h1>Cyber Security</h1><p className="sub">Centralize shared-backend security monitoring, enterprise-readiness controls, compliance checkpoints, incident history, code-health findings, and remediation status across Pie and future projects.</p></section>
    <section className="panel"><div className="controlGrid"><div className="statusBox"><small>OPEN CRITICAL</small><strong>{stats.critical}</strong></div><div className="statusBox"><small>OPEN HIGH</small><strong>{stats.high}</strong></div><div className="statusBox"><small>OPEN MEDIUM</small><strong>{stats.medium}</strong></div><div className="statusBox"><small>SECURITY EVENTS</small><strong>{stats.total}</strong></div><div className="statusBox"><small>FAILED SECURITY RUNS</small><strong>{stats.failedRuns}</strong></div></div><div style={{display:'grid',gap:6,marginTop:12}}><small><strong>Email alerts:</strong> {settings?.email_alerts_enabled?'On':'Off'}</small><small><strong>In-app alerts:</strong> {settings?.in_app_alerts_enabled===false?'Off':'On'}</small><small>Security monitoring continues in the background; this workspace is the primary log and review surface.</small></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button className="secondary" type="button" onClick={load} disabled={busy}>{busy?'Refreshing…':'↻ Refresh Security Data'}</button><button className="secondary" type="button" onClick={()=>{window.location.href='/support-admin';}}>🛟 Support Operations</button></div>{status&&<small style={{display:'block',marginTop:8}}>{status}</small>}</section>

    <section className="panel"><div className="songsSectionHead"><strong>Reusable Security Core</strong><span>{reusableSecurityCore.length}</span></div><div className="growthCardGrid" style={{marginTop:10}}>{reusableSecurityCore.map(item=><article key={item} className="growthFeatureCard"><strong>Shared control</strong><small>{item}</small></article>)}</div></section>

    <section className="panel"><div className="songsSectionHead"><strong>Enterprise Security + Compliance Roadmap</strong><span>{frameworks.length}</span></div><div className="statusBox" style={{marginTop:10}}><strong>No certification is claimed here.</strong><small style={{display:'block',marginTop:4}}>HIPAA, CMMC, SOC 2, ISO and other entries track architecture, evidence and readiness. External certification, formal assessment, contract applicability or regulated status must still be established separately for each project and system boundary.</small></div><div style={{display:'grid',gap:10,marginTop:12}}>{frameworks.map(item=>{const latest=latestCompliance[item.id];const current=draftStatus[item.id]||latest?.status||item.defaultStatus;return <article key={item.id} className="statusBox" style={{display:'grid',gap:8}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div><strong>{item.name}</strong><small style={{display:'block',marginTop:2}}>{item.priority} · {item.scope}</small></div><strong>{statusLabels[latest?.status||item.defaultStatus]}</strong></div><small>{item.purpose}</small>{item.target&&<small><strong>Target:</strong> {item.target}</small>}{item.controls&&item.controls.length>0&&<div style={{display:'grid',gap:6,marginTop:4}}>{item.controls.map(control=><div key={control.id} style={{padding:'8px 10px',border:'1px solid rgba(255,255,255,.08)',borderRadius:10}}><strong style={{fontSize:12}}>{control.name}</strong><small style={{display:'block',marginTop:2}}>{control.description}</small></div>)}</div>}{latest&&<small>Last logged: {new Date(latest.at).toLocaleString()}{latest.note?` · ${latest.note}`:''}</small>}<div className="controlGrid"><label className="controlLabel"><span>Status</span><select value={current} onChange={e=>setDraftStatus(previous=>({...previous,[item.id]:e.target.value as ComplianceStatus}))}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="evidence_gathering">Evidence gathering</option><option value="audit_ready">Audit-ready</option><option value="conditional">Conditional</option><option value="not_in_scope">Not currently in scope</option></select></label><label className="controlLabel"><span>Checkpoint note / evidence</span><input value={notes[item.id]||''} onChange={e=>setNotes(previous=>({...previous,[item.id]:e.target.value}))} placeholder="What changed, evidence collected, next gap…" /></label></div><button className="secondary" type="button" disabled={busy} onClick={()=>logCompliance(item)}>Log Compliance Checkpoint</button></article>;})}</div></section>

    <section className="panel"><h2>Enterprise Evidence Register</h2><div className="growthCardGrid"><article className="growthFeatureCard"><strong>Identity + Access</strong><small>MFA, admin separation, least privilege, access reviews, session controls, and privileged-action evidence.</small></article><article className="growthFeatureCard"><strong>Data Protection</strong><small>Encryption, data classification, retention/deletion, backups, recovery, privacy rights, and secrets management.</small></article><article className="growthFeatureCard"><strong>Secure Development</strong><small>Code review, dependency management, CodeQL, vulnerability remediation, release controls, and rollback evidence.</small></article><article className="growthFeatureCard"><strong>Monitoring + Incident Response</strong><small>Runtime alarms, event history, escalation, response playbooks, incident exercises, and post-incident remediation.</small></article><article className="growthFeatureCard"><strong>Vendor Risk</strong><small>Subprocessor inventory, data exchanged, security posture, contracts, breach obligations, BAAs where applicable, and continuity dependencies.</small></article><article className="growthFeatureCard"><strong>Audit + Due Diligence</strong><small>Policies, architecture, penetration tests, control evidence, risk register, incident history, and buyer/investor security materials.</small></article></div></section>

    <section className="panel"><div className="songsSectionHead"><strong>Recent Security Automation</strong><span>{runs.length}</span></div><div style={{display:'grid',gap:8,marginTop:10}}>{runs.length===0?<div className="statusBox">No recent security workflow data available.</div>:runs.map(r=><article key={r.id} className="statusBox" style={{display:'grid',gap:4}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{r.name}</strong><small>{r.conclusion||r.status}</small></div><small>{r.event} · {r.branch||'—'} · {r.headSha?.slice(0,8)||'—'}</small><small>{r.updatedAt?new Date(r.updatedAt).toLocaleString():''}</small></article>)}</div></section>
    <section className="panel"><div className="songsSectionHead"><strong>Security + Compliance Event Log</strong><span>{events.length}</span></div><div style={{display:'grid',gap:8,marginTop:10}}>{events.length===0?<div className="statusBox">No stored security events yet. New runtime, code-health, and compliance checkpoints will populate here.</div>:events.map(e=><article key={e.id} className="statusBox" style={{display:'grid',gap:5}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{e.title}</strong><small>{e.severity.toUpperCase()} · {e.status}</small></div>{e.summary&&<small>{e.summary}</small>}<small>{e.source}{e.workflow?` · ${e.workflow}`:''} · {new Date(e.observed_at).toLocaleString()}</small>{e.event_type!=='compliance_checkpoint'&&<small>Findings: C {e.critical_count} · H {e.high_count} · M {e.medium_count} · L {e.low_count}</small>}{e.status!=='resolved'&&e.event_type!=='compliance_checkpoint'&&<button className="secondary" type="button" onClick={()=>resolve(e.id)} disabled={busy}>Mark Resolved</button>}</article>)}</div></section>
    <section className="panel"><h2>Security Coverage</h2><div className="growthCardGrid"><article className="growthFeatureCard"><strong>Runtime Alarm</strong><small>Production endpoint and suspicious-condition checks.</small></article><article className="growthFeatureCard"><strong>CodeQL</strong><small>Static security and quality analysis for JavaScript and TypeScript.</small></article><article className="growthFeatureCard"><strong>Dependency Risk</strong><small>Scheduled production dependency audits and version-risk review.</small></article><article className="growthFeatureCard"><strong>Code Health Agent</strong><small>Weekly architecture, efficiency, maintainability, and security recommendations.</small></article><article className="growthFeatureCard"><strong>Incident History</strong><small>Persistent severity, source, timestamps, status, and remediation history.</small></article></div></section>
  </main>;
}
