'use client';

import { useEffect, useMemo, useState } from 'react';

type EventRow={id:string;source:string;event_type:string;severity:string;status:string;title:string;summary?:string;critical_count:number;high_count:number;medium_count:number;low_count:number;workflow?:string;observed_at:string;resolved_at?:string};
type WorkflowRun={id:string;name:string;status:string;conclusion:string;event:string;headSha:string;branch:string;createdAt:string;updatedAt:string;htmlUrl:string};

export default function CyberSecurityWorkspace(){
  const [events,setEvents]=useState<EventRow[]>([]);const [runs,setRuns]=useState<WorkflowRun[]>([]);const [settings,setSettings]=useState<any>(null);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  async function load(){setBusy(true);setStatus('');try{const r=await fetch('/api/security',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load Cyber Security.');setEvents(Array.isArray(d.events)?d.events:[]);setRuns(Array.isArray(d.workflowRuns)?d.workflowRuns:[]);setSettings(d.settings||null);}catch(e){setStatus(e instanceof Error?e.message:'Could not load Cyber Security.');}finally{setBusy(false);}}
  useEffect(()=>{load();},[]);
  const stats=useMemo(()=>{const open=events.filter(e=>e.status!=='resolved');return{critical:open.filter(e=>e.severity==='critical').length,high:open.filter(e=>e.severity==='high').length,medium:open.filter(e=>e.severity==='medium').length,total:events.length,failedRuns:runs.filter(r=>r.conclusion==='failure').length};},[events,runs]);
  async function resolve(id:string){setBusy(true);try{const r=await fetch('/api/security',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'resolve',id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not resolve event.');await load();}catch(e){setStatus(e instanceof Error?e.message:'Could not resolve event.');}finally{setBusy(false);}}
  return <main className="growthWorkspace">
    <section className="hero"><p className="eyebrow">Security Operations</p><h1>Cyber Security</h1><p className="sub">Centralize Pie security monitoring, code-health findings, runtime alarms, dependency/security analysis, incident history, and remediation status without flooding your email.</p></section>
    <section className="panel"><div className="controlGrid"><div className="statusBox"><small>OPEN CRITICAL</small><strong>{stats.critical}</strong></div><div className="statusBox"><small>OPEN HIGH</small><strong>{stats.high}</strong></div><div className="statusBox"><small>OPEN MEDIUM</small><strong>{stats.medium}</strong></div><div className="statusBox"><small>SECURITY EVENTS</small><strong>{stats.total}</strong></div><div className="statusBox"><small>FAILED SECURITY RUNS</small><strong>{stats.failedRuns}</strong></div></div><div style={{display:'grid',gap:6,marginTop:12}}><small><strong>Email alerts:</strong> {settings?.email_alerts_enabled?'On':'Off'}</small><small><strong>In-app alerts:</strong> {settings?.in_app_alerts_enabled===false?'Off':'On'}</small><small>Security monitoring continues in the background; this workspace is the primary log and review surface.</small></div><button className="secondary" type="button" onClick={load} disabled={busy} style={{marginTop:12}}>{busy?'Refreshing…':'↻ Refresh Security Data'}</button>{status&&<small style={{display:'block',marginTop:8}}>{status}</small>}</section>
    <section className="panel"><div className="songsSectionHead"><strong>Recent Security Automation</strong><span>{runs.length}</span></div><div style={{display:'grid',gap:8,marginTop:10}}>{runs.length===0?<div className="statusBox">No recent security workflow data available.</div>:runs.map(r=><article key={r.id} className="statusBox" style={{display:'grid',gap:4}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{r.name}</strong><small>{r.conclusion||r.status}</small></div><small>{r.event} · {r.branch||'—'} · {r.headSha?.slice(0,8)||'—'}</small><small>{r.updatedAt?new Date(r.updatedAt).toLocaleString():''}</small></article>)}</div></section>
    <section className="panel"><div className="songsSectionHead"><strong>Security Event Log</strong><span>{events.length}</span></div><div style={{display:'grid',gap:8,marginTop:10}}>{events.length===0?<div className="statusBox">No stored security events yet. New runtime and code-health findings will populate here as in-app ingestion is connected.</div>:events.map(e=><article key={e.id} className="statusBox" style={{display:'grid',gap:5}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{e.title}</strong><small>{e.severity.toUpperCase()} · {e.status}</small></div>{e.summary&&<small>{e.summary}</small>}<small>{e.source}{e.workflow?` · ${e.workflow}`:''} · {new Date(e.observed_at).toLocaleString()}</small><small>Findings: C {e.critical_count} · H {e.high_count} · M {e.medium_count} · L {e.low_count}</small>{e.status!=='resolved'&&<button className="secondary" type="button" onClick={()=>resolve(e.id)} disabled={busy}>Mark Resolved</button>}</article>)}</div></section>
    <section className="panel"><h2>Security Coverage</h2><div className="growthCardGrid"><article className="growthFeatureCard"><strong>Runtime Alarm</strong><small>Production endpoint and suspicious-condition checks.</small></article><article className="growthFeatureCard"><strong>CodeQL</strong><small>Static security and quality analysis for JavaScript and TypeScript.</small></article><article className="growthFeatureCard"><strong>Dependency Risk</strong><small>Scheduled production dependency audits and version-risk review.</small></article><article className="growthFeatureCard"><strong>Code Health Agent</strong><small>Weekly architecture, efficiency, maintainability, and security recommendations.</small></article><article className="growthFeatureCard"><strong>Incident History</strong><small>Persistent severity, source, timestamps, status, and remediation history.</small></article></div></section>
  </main>;
}
