'use client';

import { useEffect,useState } from 'react';
type WindowRow={days:number;inflow:number;outflow:number;net:number;transactions:number;topExpenseCategories:{category:string;amount:number}[]};
type Insights={connectedAccounts:number;cashBalance:number;creditBalance:number;uncategorized:number;windows:WindowRow[];asOf:string};
export default function FinancialIntelligencePanel(){const [data,setData]=useState<Insights|null>(null);const [status,setStatus]=useState('');
useEffect(()=>{fetch('/api/finance/insights',{cache:'no-store'}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Financial insights unavailable.');setData(d);}).catch(e=>setStatus(e instanceof Error?e.message:'Financial insights unavailable.'));},[]);
if(!data)return <section className="panel"><p className="eyebrow">Financial Intelligence</p><h2>Cash Flow + Profitability</h2><small>{status||'Connect Plaid to activate automatic financial intelligence.'}</small></section>;
const w30=data.windows.find(w=>w.days===30);const w90=data.windows.find(w=>w.days===90);
return <section className="panel"><p className="eyebrow">Financial Intelligence</p><h2>Cash Flow + Profitability</h2><div className="controlGrid"><div className="statusBox"><small>CONNECTED CASH</small><strong>${data.cashBalance.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="statusBox"><small>CREDIT BALANCE</small><strong>${data.creditBalance.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="statusBox"><small>30-DAY NET FLOW</small><strong>${Number(w30?.net||0).toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="statusBox"><small>UNCATEGORIZED</small><strong>{data.uncategorized}</strong></div></div>{w30&&<div style={{display:'grid',gap:8,marginTop:12}}><strong>Last 30 Days</strong><small>Inflow ${w30.inflow.toLocaleString()} · Outflow ${w30.outflow.toLocaleString()} · {w30.transactions} posted transactions</small>{w30.topExpenseCategories.map(x=><small key={x.category}>{x.category.replaceAll('_',' ')} · ${x.amount.toLocaleString()}</small>)}</div>}{w90&&<div style={{display:'grid',gap:4,marginTop:12}}><strong>90-Day View</strong><small>Inflow ${w90.inflow.toLocaleString()} · Outflow ${w90.outflow.toLocaleString()} · Net ${w90.net.toLocaleString()}</small></div>}<small style={{display:'block',marginTop:12,color:'#8f90a2'}}>Pie treats negative Plaid transaction amounts as inflows and positive amounts as outflows, excludes pending transactions, and keeps this analysis private to the signed-in Pie account.</small></section>;
}
