'use client';

import { useEffect, useMemo, useState } from 'react';

declare global { interface Window { Plaid?: { create: (options: Record<string, unknown>) => { open: () => void; destroy?: () => void } } } }

type Connection={id:string;institution_name?:string;status:string;last_synced_at?:string;error_message?:string};
type Account={id:string;connection_id:string;name?:string;official_name?:string;mask?:string;account_type?:string;account_subtype?:string;current_balance?:number;available_balance?:number;currency?:string};
type Tx={id:string;account_id?:string;transaction_date?:string;name?:string;merchant_name?:string;amount?:number;currency?:string;category?:string;pending?:boolean};

export default function PlaidConnectPanel(){
  const [configured,setConfigured]=useState<boolean|null>(null);const [connections,setConnections]=useState<Connection[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [transactions,setTransactions]=useState<Tx[]>([]);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  async function getStatus(){try{const r=await fetch('/api/plaid/status',{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load Plaid status.');setConfigured(Boolean(d.configured));setConnections(Array.isArray(d.connections)?d.connections:[]);setAccounts(Array.isArray(d.accounts)?d.accounts:[]);setTransactions(Array.isArray(d.transactions)?d.transactions:[]);}catch(e){setStatus(e instanceof Error?e.message:'Could not load Plaid status.');}}
  useEffect(()=>{getStatus();},[]);
  useEffect(()=>{if(document.getElementById('plaid-link-script'))return;const s=document.createElement('script');s.id='plaid-link-script';s.src='https://cdn.plaid.com/link/v2/stable/link-initialize.js';s.async=true;document.head.appendChild(s);},[]);
  const connectedBalance=useMemo(()=>accounts.reduce((sum,a)=>sum+Number(a.current_balance||0),0),[accounts]);
  async function connect(){setBusy(true);setStatus('');try{const r=await fetch('/api/plaid/link-token',{method:'POST'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not start Plaid Link.');if(!window.Plaid)throw new Error('Plaid Link is still loading. Try again in a moment.');const handler=window.Plaid.create({token:d.link_token,onSuccess:async(publicToken:string,metadata:any)=>{setStatus('Connecting account…');const x=await fetch('/api/plaid/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicToken,institutionId:metadata?.institution?.institution_id,institutionName:metadata?.institution?.name})});const xd=await x.json().catch(()=>({}));if(!x.ok)throw new Error(xd.error||'Bank connection failed.');await sync(String(xd.connectionId||''),false);setStatus('Bank connected and synced.');},onExit:(err:any)=>{if(err)setStatus(err.display_message||err.error_message||'Plaid Link closed with an error.');setBusy(false);}});handler.open();}catch(e){setStatus(e instanceof Error?e.message:'Could not connect bank.');setBusy(false);}}
  async function sync(connectionId:string,show=true){if(!connectionId)return;setBusy(true);if(show)setStatus('Syncing transactions…');try{const r=await fetch('/api/plaid/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectionId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Sync failed.');await getStatus();if(show)setStatus(`Sync complete · ${d.added||0} added · ${d.modified||0} updated.`);}catch(e){setStatus(e instanceof Error?e.message:'Sync failed.');}finally{setBusy(false);}}
  async function disconnect(connectionId:string){if(!confirm('Disconnect this bank from Pie?'))return;setBusy(true);try{const r=await fetch('/api/plaid/disconnect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectionId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Disconnect failed.');await getStatus();setStatus('Bank disconnected.');}catch(e){setStatus(e instanceof Error?e.message:'Disconnect failed.');}finally{setBusy(false);}}
  return <section className="panel"><p className="eyebrow">Connected Banking</p><h2>Bank Accounts + Transactions</h2><p className="sub">Connect business bank and card accounts through Plaid so Pie can reconcile transactions, cash flow, expenses, royalties, tax records, budgets, and profitability.</p>
    {configured===false&&<div className="statusBox" style={{marginBottom:12}}><strong>Plaid setup required</strong><small>Add PLAID_CLIENT_ID, PLAID_SECRET, PLAID_ENV, and PLAID_TOKEN_ENCRYPTION_KEY in Vercel before connecting a bank.</small></div>}
    <div className="controlGrid"><div className="statusBox"><small>CONNECTIONS</small><strong>{connections.length}</strong></div><div className="statusBox"><small>ACCOUNTS</small><strong>{accounts.length}</strong></div><div className="statusBox"><small>CONNECTED BALANCE</small><strong>${connectedBalance.toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><div className="statusBox"><small>SYNCED TRANSACTIONS</small><strong>{transactions.length}</strong></div></div>
    <div className="mixButtons" style={{marginTop:12}}><button type="button" className="primary" onClick={connect} disabled={busy||configured===false}>＋ Connect Bank</button>{connections.map(c=><button key={c.id} type="button" className="secondary" onClick={()=>sync(c.id)} disabled={busy}>↻ Sync {c.institution_name||'Bank'}</button>)}</div>
    {connections.length>0&&<div style={{display:'grid',gap:8,marginTop:12}}>{connections.map(c=><article key={c.id} className="statusBox" style={{display:'grid',gap:5}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{c.institution_name||'Connected institution'}</strong><small>{c.status}</small></div><small>{c.last_synced_at?`Last synced ${new Date(c.last_synced_at).toLocaleString()}`:'Not synced yet'}</small>{c.error_message&&<small style={{color:'#ffb5c0'}}>{c.error_message}</small>}<button type="button" className="secondary" onClick={()=>disconnect(c.id)} disabled={busy}>Disconnect</button></article>)}</div>}
    {accounts.length>0&&<div style={{display:'grid',gap:8,marginTop:14}}><div className="songsSectionHead"><strong>Accounts</strong><span>{accounts.length}</span></div>{accounts.map(a=><article key={a.id} className="statusBox"><strong>{a.official_name||a.name||'Account'}{a.mask?` •••• ${a.mask}`:''}</strong><small>{a.account_type||''}{a.account_subtype?` · ${a.account_subtype}`:''} · ${(a.currency||'USD')} · Current ${Number(a.current_balance||0).toLocaleString(undefined,{style:'currency',currency:a.currency||'USD'})}</small></article>)}</div>}
    {transactions.length>0&&<div style={{display:'grid',gap:8,marginTop:14}}><div className="songsSectionHead"><strong>Recent Bank Activity</strong><span>{transactions.length}</span></div>{transactions.slice(0,25).map(t=><article key={t.id} className="statusBox" style={{display:'grid',gap:3}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{t.merchant_name||t.name||'Transaction'}</strong><strong>${Number(t.amount||0).toLocaleString(undefined,{maximumFractionDigits:2})}</strong></div><small>{t.transaction_date||''}{t.category?` · ${t.category.replaceAll('_',' ')}`:''}{t.pending?' · Pending':''}</small></article>)}</div>}
    {status&&<div style={{marginTop:12}} className="statusBox"><small>{status}</small></div>}
    <small style={{display:'block',marginTop:12,color:'#8f90a2'}}>Pie stores the Plaid access token encrypted server-side and does not expose it to the browser. Connected financial data remains private to the signed-in Pie account.</small>
  </section>;
}
