'use client';

import { useEffect, useState } from 'react';

type ScoreNote={midi:number;startBeat:number;durationBeats:number;velocity:number};
type ScorePart={name:string;instrument:string;isVocal:boolean;choirRole?:string;lyrics?:string;notes:ScoreNote[]};
type ImportedScore={title:string;composer?:string;tempo:number;key?:string;timeSignature?:string;style?:string;lyrics?:string;parts:ScorePart[]};
type Rendered={key:string;label:string;url:string};

function keyFor(part:ScorePart,index:number){return `part:${index}:${part.choirRole||part.instrument||part.name}`}
function labelFor(part:ScorePart){const r=(part.choirRole||'').toLowerCase();if(r==='bass')return 'Choir Bass';if(r)return r[0].toUpperCase()+r.slice(1);return part.name||part.instrument||'Part'}
function hz(midi:number){return 440*Math.pow(2,(midi-69)/12)}
function wave(part:ScorePart):OscillatorType{const n=`${part.name} ${part.instrument}`.toLowerCase();if(part.isVocal||part.choirRole)return 'sine';if(n.includes('bass'))return 'triangle';if(n.includes('guitar')||n.includes('string'))return 'sawtooth';if(n.includes('drum')||n.includes('perc'))return 'square';return 'triangle'}
function wav(buffer:AudioBuffer){const channels=buffer.numberOfChannels,length=buffer.length*channels*2+44,array=new ArrayBuffer(length),view=new DataView(array);const write=(o:number,t:string)=>{for(let i=0;i<t.length;i++)view.setUint8(o+i,t.charCodeAt(i))};write(0,'RIFF');view.setUint32(4,length-8,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,length-44,true);const data=Array.from({length:channels},(_,c)=>buffer.getChannelData(c));let o=44;for(let i=0;i<buffer.length;i++)for(let c=0;c<channels;c++){const s=Math.max(-1,Math.min(1,data[c][i]||0));view.setInt16(o,s<0?s*0x8000:s*0x7fff,true);o+=2}return new Blob([array],{type:'audio/wav'})}
async function render(score:ImportedScore,parts:ScorePart[]){const spb=60/Math.max(35,score.tempo||100);const maxBeat=parts.flatMap(p=>p.notes).reduce((m,n)=>Math.max(m,n.startBeat+n.durationBeats),0);const duration=Math.min(600,Math.max(1,maxBeat*spb+1));const ctx=new OfflineAudioContext(1,Math.ceil(duration*22050),22050);const master=ctx.createGain();master.gain.value=Math.min(.85,1/Math.max(1,Math.sqrt(parts.length)));master.connect(ctx.destination);for(const part of parts){const pg=ctx.createGain();pg.gain.value=part.isVocal?.65:.52;pg.connect(master);for(const note of part.notes){const start=note.startBeat*spb;if(start>=duration)continue;const d=Math.max(.05,Math.min(8,note.durationBeats*spb));const osc=ctx.createOscillator(),g=ctx.createGain();osc.type=wave(part);osc.frequency.value=hz(note.midi);const level=Math.max(.015,Math.min(.16,(note.velocity||.7)*.11));g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(level,start+.015);g.gain.setValueAtTime(level,Math.max(start+.02,start+d*.78));g.gain.exponentialRampToValueAtTime(.0001,Math.min(duration,start+d));osc.connect(g);g.connect(pg);osc.start(start);osc.stop(Math.min(duration,start+d+.03))}}return wav(await ctx.startRendering())}

export default function ScoreImportWorkspace(){
  const [score,setScore]=useState<ImportedScore|null>(null),[status,setStatus]=useState(''),[reading,setReading]=useState(false),[rendering,setRendering]=useState(false);
  const [selected,setSelected]=useState<Set<string>>(new Set()),[rendered,setRendered]=useState<Rendered[]>([]);
  useEffect(()=>()=>rendered.forEach(r=>URL.revokeObjectURL(r.url)),[rendered]);
  async function read(file:File){setReading(true);setScore(null);setSelected(new Set());setRendered([]);setStatus('Reading score and identifying every written part…');try{const f=new FormData();f.append('file',file,file.name);const r=await fetch('/api/sheets/import-score',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not read score.');setScore(d.score);setStatus(`Found ${d.score.parts.length} written part${d.score.parts.length===1?'':'s'}. Choose what you want to render.`)}catch(e){setStatus(e instanceof Error?e.message:'Could not read score.')}finally{setReading(false)}}
  function toggle(k:string){setSelected(s=>{const n=new Set(s);n.has(k)?n.delete(k):n.add(k);return n})}
  async function renderSelected(){if(!score||!selected.size)return;setRendering(true);rendered.forEach(r=>URL.revokeObjectURL(r.url));setRendered([]);setStatus('Rendering selected written parts…');try{const out:Rendered[]=[];if(selected.has('full')){const b=await render(score,score.parts);out.push({key:'full',label:'Full Arrangement',url:URL.createObjectURL(b)})}for(let i=0;i<score.parts.length;i++){const p=score.parts[i],k=keyFor(p,i);if(!selected.has(k))continue;const b=await render(score,[p]);out.push({key:k,label:labelFor(p),url:URL.createObjectURL(b)})}setRendered(out);setStatus(`Rendered ${out.length} selected part${out.length===1?'':'s'}.`)}catch(e){setStatus(e instanceof Error?e.message:'Could not render score.')}finally{setRendering(false)}}
  const choir=score?.parts.map((part,index)=>({part,index})).filter(x=>x.part.choirRole)||[];const others=score?.parts.map((part,index)=>({part,index})).filter(x=>!x.part.choirRole)||[];
  return <div className="sheetSourceCard noPrint scoreImportCard"><p className="eyebrow">Sheet → Song</p><h2>Upload Music Sheets</h2><p className="sub">Pie reads the score first. <strong>Nothing renders until you answer: “What parts do you want to render?”</strong></p><label className="primary scoreUploadButton">{reading?'Reading score…':'⬆ Upload Music Sheets'}<input hidden type="file" accept="application/pdf,image/*,.musicxml,.xml,application/xml,text/xml" disabled={reading||rendering} onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.currentTarget.value=''}}/></label>{score&&<div className="scorePartChooser"><div className="scoreImportSummary"><strong>{score.title}</strong><small>{score.tempo} BPM · {score.key||'Key unknown'} · {score.timeSignature||'4/4'}</small></div><h3>What parts do you want to render?</h3><div className="renderPartGrid"><label className={selected.has('full')?'renderPartChoice selected':'renderPartChoice'}><input type="checkbox" checked={selected.has('full')} onChange={()=>toggle('full')}/><span>🎼</span><strong>Full Arrangement</strong></label></div>{choir.length>0&&<><h4>Choir</h4><div className="renderPartGrid">{choir.map(({part,index})=>{const k=keyFor(part,index);return <label key={k} className={selected.has(k)?'renderPartChoice selected':'renderPartChoice'}><input type="checkbox" checked={selected.has(k)} onChange={()=>toggle(k)}/><span>🎤</span><strong>{labelFor(part)}</strong><small>{part.name}</small></label>})}</div></>}{others.length>0&&<><h4>Vocals & Instruments</h4><div className="renderPartGrid">{others.map(({part,index})=>{const k=keyFor(part,index);return <label key={k} className={selected.has(k)?'renderPartChoice selected':'renderPartChoice'}><input type="checkbox" checked={selected.has(k)} onChange={()=>toggle(k)}/><span>{part.isVocal?'🎤':'🎵'}</span><strong>{labelFor(part)}</strong><small>{part.instrument}</small></label>})}</div></>}<button className="primary" disabled={rendering||!selected.size} onClick={()=>void renderSelected()}>{rendering?'Rendering…':`▶ Render Selected Parts${selected.size?` (${selected.size})`:''}`}</button></div>}{rendered.length>0&&<div className="renderedScoreParts"><h3>Rendered Parts</h3>{rendered.map(r=><div className="renderedScoreRow" key={r.key}><strong>{r.label}</strong><audio controls src={r.url}/><a className="secondary" href={r.url} download={`${(score?.title||'score').replace(/[^a-z0-9_-]+/gi,'-')}-${r.label.replace(/[^a-z0-9_-]+/gi,'-')}.wav`}>Download WAV</a></div>)}</div>}{status&&<div className="statusBox">{status}</div>}</div>
}
