'use client';

import { FormEvent, useEffect, useState } from 'react';

const contractTypes=['Band Partnership / Operating Agreement','Artist Management Agreement','Producer Agreement','Featured Artist Agreement','Songwriter Split Sheet','Work-for-Hire / Contractor Agreement','Master Ownership / Assignment Agreement','Publishing Administration Agreement','Co-Publishing Agreement','Synchronization / Master Use License','Booking / Live Performance Agreement','Brand Endorsement / Sponsorship Agreement','Merchandise License Agreement','Distribution Agreement Review Draft','NDA / Confidentiality Agreement','IP Assignment / License Agreement','Collaboration Agreement','Tax + Accounting Professional Engagement Letter'];
type Saved={id:string;title:string;contract_type:string;jurisdiction?:string;status:string;created_at:string;updated_at:string};

export default function ContractsPage(){
  const [contractType,setContractType]=useState(contractTypes[0]);const [jurisdiction,setJurisdiction]=useState('Washington, USA');const [parties,setParties]=useState('');const [dealTerms,setDealTerms]=useState('');const [protections,setProtections]=useState('');const [taxNotes,setTaxNotes]=useState('');const [ipNotes,setIpNotes]=useState('');const [negotiationPosition,setNegotiationPosition]=useState('Artist-protective and commercially reasonable');const [draft,setDraft]=useState('');const [saved,setSaved]=useState<Saved[]>([]);const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  async function operations(action:string,extra:Record<string,unknown>={}){const r=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
  async function loadSaved(){try{const d=await operations('contractList');setSaved(Array.isArray(d.contracts)?d.contracts:[]);}catch{}}
  useEffect(()=>{loadSaved();},[]);
  async function generate(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const r=await fetch('/api/contracts/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contractType,jurisdiction,parties,dealTerms,protections,taxNotes,ipNotes,negotiationPosition})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Drafting failed.');setDraft(d.text||'');setStatus(d.disclaimer||'Draft generated.');}catch(err){setStatus(err instanceof Error?err.message:'Drafting failed.');}finally{setBusy(false);}}
  async function save(){if(!draft.trim())return;setBusy(true);try{await operations('contractSave',{title:`${contractType} · ${new Date().toLocaleDateString()}`,contractType,jurisdiction,parties:parties.split('\n').filter(Boolean),dealTerms:{summary:dealTerms,taxNotes,ipNotes,protections,negotiationPosition},draftText:draft});setStatus('Draft saved to your private Pie legal workspace.');await loadSaved();}catch(err){setStatus(err instanceof Error?err.message:'Could not save draft.');}finally{setBusy(false);}}
  return <main style={{minHeight:'100vh',background:'#080910',color:'#fff',padding:'20px 14px 60px'}}><div style={{width:'min(100%,1050px)',margin:'0 auto',display:'grid',gap:16}}>
    <header><a href="/" style={{color:'#a78bfa',textDecoration:'none'}}>← Back to Pie</a><h1 style={{fontSize:34,margin:'12px 0 5px'}}>⚖️ Pie Contract Studio</h1><p style={{color:'#9ca3af',lineHeight:1.5}}>Advanced entertainment, business, tax-coordination, and intellectual-property drafting with strong issue-spotting and negotiation notes. Every draft is built for professional review before signature.</p></header>
    <section style={panel}><form onSubmit={generate} style={{display:'grid',gap:12}}><div style={grid}><label style={label}>Agreement type<select value={contractType} onChange={e=>setContractType(e.target.value)} style={input}>{contractTypes.map(x=><option key={x}>{x}</option>)}</select></label><label style={label}>Jurisdiction / governing law<input value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)} style={input}/></label></div><label style={label}>Parties and roles<textarea value={parties} onChange={e=>setParties(e.target.value)} style={{...input,minHeight:90}} placeholder="Artist LLC; Manager LLC; producer; band members; brand…"/></label><label style={label}>Deal terms<textarea value={dealTerms} onChange={e=>setDealTerms(e.target.value)} style={{...input,minHeight:130}} placeholder="Compensation, term, territory, ownership, royalty, approvals, deliverables, options, exclusivity…"/></label><div style={grid}><label style={label}>Protections<textarea value={protections} onChange={e=>setProtections(e.target.value)} style={{...input,minHeight:100}} placeholder="Approval rights, audit, termination, caps, indemnity limits…"/></label><label style={label}>IP protections<textarea value={ipNotes} onChange={e=>setIpNotes(e.target.value)} style={{...input,minHeight:100}} placeholder="Masters, compositions, trademarks, likeness, artwork, pre-existing IP…"/></label><label style={label}>Tax + accounting issues<textarea value={taxNotes} onChange={e=>setTaxNotes(e.target.value)} style={{...input,minHeight:100}} placeholder="Withholding, reporting, expenses, audit, payment timing, entity treatment…"/></label><label style={label}>Negotiation position<textarea value={negotiationPosition} onChange={e=>setNegotiationPosition(e.target.value)} style={{...input,minHeight:100}}/></label></div><button disabled={busy} style={primary}>{busy?'Drafting…':'Generate Advanced Draft'}</button></form></section>
    <section style={panel}><h2>Draft</h2>{draft?<><textarea value={draft} onChange={e=>setDraft(e.target.value)} style={{...input,minHeight:650,fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace',lineHeight:1.55}}/><button type="button" onClick={save} disabled={busy} style={{...primary,marginTop:10}}>Save Private Draft</button></>:<p style={{color:'#9ca3af'}}>Your generated agreement, issue-spotter, negotiation notes, and counsel-review checklist will appear here.</p>}{status&&<p style={{color:'#c4b5fd',lineHeight:1.5}}>{status}</p>}<div style={{marginTop:12,padding:12,borderRadius:12,background:'#17121f',color:'#d7c9ff',fontSize:12,lineHeight:1.5}}>Pie drafts documents; it does not replace licensed entertainment counsel or tax professionals. Do not sign or rely on a generated agreement without appropriate professional review.</div></section>
    <section style={panel}><h2>Saved Drafts</h2>{saved.length===0?<p style={{color:'#9ca3af'}}>No saved drafts yet.</p>:<div style={{display:'grid',gap:8}}>{saved.map(x=><article key={x.id} style={{padding:12,borderRadius:12,background:'#0d0f16',border:'1px solid #2b2d3a'}}><strong>{x.title}</strong><small style={{display:'block',color:'#9ca3af',marginTop:4}}>{x.contract_type} · {x.jurisdiction||'Jurisdiction not set'} · {new Date(x.updated_at).toLocaleString()}</small></article>)}</div>}</section>
  </div></main>;
}
const panel:React.CSSProperties={padding:18,borderRadius:20,background:'#11131b',border:'1px solid #292c39'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10};const label:React.CSSProperties={display:'grid',gap:6,fontSize:12,fontWeight:800};const input:React.CSSProperties={width:'100%',padding:'12px',borderRadius:12,border:'1px solid #343746',background:'#090a10',color:'#fff'};const primary:React.CSSProperties={minHeight:50,border:0,borderRadius:12,background:'#7c3aed',color:'#fff',fontWeight:900};
