'use client';

import { FormEvent, useEffect, useState } from 'react';
type SupportCase={id:string;case_number:string;support_type:string;business_stage?:string;preferred_contact?:string;subject:string;message:string;status:string;priority:string;assigned_to?:string;specialist_type?:string;escalation_level?:number;next_response_due_at?:string;appointment_requested?:boolean;first_response_at?:string;last_staff_reply_at?:string;last_user_reply_at?:string;created_at:string;updated_at:string;closed_at?:string};
type Message={id:string;sender_role:string;body:string;created_at:string};
const supportTypes=['Backend setup + account connections','Coaching + strategy','Sales + booking','Tax + accounting','Legal + contracts','Marketing + growth','Distribution + release setup','Merch + e-commerce','Gigs + touring operations','Team + contractor setup','Funding + budgeting','Other / help me figure it out'];
const stages=['1 · Raw Talent','2 · Hot Prospect','3 · Talent Show Boss','4 · Local Hero','5 · Regional Hit','6 · National Hitmaker','7 · International Rock Star','8 · World Legend'];
const specialistLabels:Record<string,string>={entertainment_counsel:'Entertainment Legal',tax_accounting:'Tax + Accounting',booking_live:'Booking + Live',technical:'Technical',growth_distribution:'Growth + Distribution',finance_strategy:'Finance Strategy',general_artist_support:'Artist Support'};

export default function SupportPage(){
  const [cases,setCases]=useState<SupportCase[]>([]);const [selected,setSelected]=useState<SupportCase|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [supportType,setSupportType]=useState(supportTypes[0]);const [stage,setStage]=useState(stages[0]);const [contact,setContact]=useState('Email');const [subject,setSubject]=useState('');const [message,setMessage]=useState('');const [reply,setReply]=useState('');const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  async function call(action:string,extra:Record<string,unknown>={}){const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Support request failed.');return d;}
  async function loadCases(){try{const d=await call('list');setCases(Array.isArray(d.cases)?d.cases:[]);if(selected){const next=(d.cases||[]).find((c:SupportCase)=>c.id===selected.id);if(next)setSelected(next);}}catch(e){setStatus(e instanceof Error?e.message:'Could not load support cases.');}}
  async function openCase(item:SupportCase){setSelected(item);try{const d=await call('messages',{caseId:item.id});setMessages(Array.isArray(d.messages)?d.messages:[]);}catch(e){setStatus(e instanceof Error?e.message:'Could not load case history.');}}
  useEffect(()=>{loadCases();},[]);
  async function createCase(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const d=await call('create',{supportType,businessStage:stage,preferredContact:contact,subject,message,priority:'normal'});setSubject('');setMessage('');setStatus(`Case ${d.case.case_number} created and routed to ${specialistLabels[d.case.specialist_type]||'Pie Support'}.`);await loadCases();await openCase(d.case);}catch(err){setStatus(err instanceof Error?err.message:'Could not create case.');}finally{setBusy(false);}}
  async function sendReply(e:FormEvent){e.preventDefault();if(!selected||!reply.trim())return;setBusy(true);try{await call('reply',{caseId:selected.id,message:reply});setReply('');await openCase(selected);await loadCases();}catch(err){setStatus(err instanceof Error?err.message:'Could not send reply.');}finally{setBusy(false);}}
  async function requestAppointment(){if(!selected)return;setBusy(true);try{await call('appointment',{caseId:selected.id});setStatus('Professional appointment request added to this case.');await loadCases();}catch(err){setStatus(err instanceof Error?err.message:'Could not request appointment.');}finally{setBusy(false);}}
  return <main style={{minHeight:'100vh',background:'#080910',color:'#fff',padding:'20px 14px 50px'}}><div style={{width:'min(100%,980px)',margin:'0 auto',display:'grid',gap:16}}>
    <header><a href="/" style={{color:'#a78bfa',textDecoration:'none'}}>← Back to Pie</a><h1 style={{fontSize:34,margin:'12px 0 4px'}}>🛟 Live Support</h1><p style={{color:'#9ca3af'}}>Cases are saved, routed by specialty, tracked against a response window, and kept with the full conversation history.</p></header>
    <section style={panel}><h2>New Support Case</h2><form onSubmit={createCase} style={{display:'grid',gap:10}}><div style={grid}><label style={label}>Support area<select value={supportType} onChange={e=>setSupportType(e.target.value)} style={input}>{supportTypes.map(x=><option key={x}>{x}</option>)}</select></label><label style={label}>Pie stage<select value={stage} onChange={e=>setStage(e.target.value)} style={input}>{stages.map(x=><option key={x}>{x}</option>)}</select></label><label style={label}>Preferred contact<select value={contact} onChange={e=>setContact(e.target.value)} style={input}><option>Email</option><option>Phone</option><option>Video call</option><option>In-app message</option></select></label></div><label style={label}>Subject<input required maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)} style={input}/></label><label style={label}>What do you need?<textarea required maxLength={6000} value={message} onChange={e=>setMessage(e.target.value)} style={{...input,minHeight:130}}/></label><button disabled={busy} style={primary}>{busy?'Creating…':'Create Support Case'}</button></form>{status&&<p style={{color:'#c4b5fd'}}>{status}</p>}</section>
    <section style={panel}><h2>Case History</h2>{cases.length===0?<p style={{color:'#9ca3af'}}>No cases yet.</p>:<div style={{display:'grid',gap:8}}>{cases.map(item=><button key={item.id} onClick={()=>openCase(item)} style={{...caseButton,borderColor:selected?.id===item.id?'#8b5cf6':'#2b2d3a'}}><div><strong>{item.case_number} · {item.subject}</strong><small style={{display:'block',color:'#9ca3af',marginTop:4}}>{specialistLabels[item.specialist_type||'']||item.support_type} · {item.status} · {new Date(item.updated_at).toLocaleString()}</small>{item.next_response_due_at&&<small style={{display:'block',color:'#c4b5fd',marginTop:3}}>Response target: {new Date(item.next_response_due_at).toLocaleString()}</small>}</div><span>{item.priority}</span></button>)}</div>}</section>
    {selected&&<section style={panel}><h2>{selected.case_number} · {selected.subject}</h2><div style={grid}><div style={info}><small>ROUTED TO</small><strong>{specialistLabels[selected.specialist_type||'']||selected.support_type}</strong></div><div style={info}><small>PRIORITY</small><strong>{selected.priority}</strong></div><div style={info}><small>STATUS</small><strong>{selected.status}</strong></div><div style={info}><small>ESCALATION</small><strong>Level {selected.escalation_level||0}</strong></div></div>{selected.appointment_requested?<p style={{color:'#c4b5fd'}}>✓ Professional appointment requested</p>:<button type="button" onClick={requestAppointment} disabled={busy} style={{...secondary,margin:'12px 0'}}>Request Professional Appointment</button>}<div style={{display:'grid',gap:8}}>{messages.map(m=><article key={m.id} style={{padding:12,borderRadius:14,background:m.sender_role==='user'?'#17132a':'#101923',border:'1px solid #2b2d3a'}}><strong>{m.sender_role==='user'?'You':'Pie Support'}</strong><p style={{whiteSpace:'pre-wrap',lineHeight:1.5}}>{m.body}</p><small style={{color:'#888'}}>{new Date(m.created_at).toLocaleString()}</small></article>)}</div><form onSubmit={sendReply} style={{display:'grid',gap:8,marginTop:12}}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Add a reply…" style={{...input,minHeight:100}}/><button disabled={busy||!reply.trim()} style={primary}>Send Reply</button></form></section>}
  </div></main>;
}
const panel:React.CSSProperties={padding:18,borderRadius:20,background:'#11131b',border:'1px solid #292c39'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10};const label:React.CSSProperties={display:'grid',gap:6,fontSize:12,fontWeight:800};const input:React.CSSProperties={width:'100%',padding:'12px',borderRadius:12,border:'1px solid #343746',background:'#090a10',color:'#fff'};const primary:React.CSSProperties={minHeight:48,border:0,borderRadius:12,background:'#7c3aed',color:'#fff',fontWeight:900};const secondary:React.CSSProperties={minHeight:42,padding:'0 14px',borderRadius:12,border:'1px solid #343746',background:'#171923',color:'#fff',fontWeight:800};const info:React.CSSProperties={padding:12,borderRadius:12,background:'#0d0f16',border:'1px solid #2b2d3a',display:'grid',gap:4};const caseButton:React.CSSProperties={width:'100%',display:'flex',justifyContent:'space-between',gap:12,textAlign:'left',padding:12,borderRadius:14,border:'1px solid',background:'#0d0f16',color:'#fff'};
