'use client';

import { useEffect,useState } from 'react';
type Case={id:string;user_id:string;case_number:string;support_type:string;subject:string;status:string;priority:string;assigned_to?:string;specialist_type?:string;escalation_level?:number;next_response_due_at?:string;appointment_requested?:boolean;updated_at:string};
const specialists=['general_artist_support','technical','entertainment_counsel','tax_accounting','booking_live','growth_distribution','finance_strategy'];
export default function SupportAdmin(){const [cases,setCases]=useState<Case[]>([]);const [selected,setSelected]=useState<Case|null>(null);const [reply,setReply]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
async function call(action:string,extra:Record<string,unknown>={}){const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Support admin request failed.');return d;}
async function load(){try{const d=await call('adminQueue');setCases(Array.isArray(d.cases)?d.cases:[]);}catch(e){setStatus(e instanceof Error?e.message:'Could not load support queue.');}}
useEffect(()=>{load();},[]);
async function update(extra:Record<string,unknown>){if(!selected)return;setBusy(true);try{await call('adminUpdate',{caseId:selected.id,...extra});setStatus('Case updated.');await load();setSelected(s=>s?{...s,...extra} as Case:s);}catch(e){setStatus(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
async function send(){if(!selected||!reply.trim())return;setBusy(true);try{await call('adminReply',{caseId:selected.id,message:reply});setReply('');setStatus('Reply sent.');await load();}catch(e){setStatus(e instanceof Error?e.message:'Reply failed.');}finally{setBusy(false);}}
return <main style={{minHeight:'100vh',background:'#080910',color:'#fff',padding:'20px 14px 60px'}}><div style={{width:'min(100%,1150px)',margin:'0 auto',display:'grid',gap:16}}><header><a href="/support" style={{color:'#a78bfa'}}>← Live Support</a><h1>🛟 Support Operations</h1><p style={{color:'#9ca3af'}}>Internal queue for assignment, specialist routing, escalation, appointment requests, and response deadlines.</p></header>{status&&<div style={panel}>{status}</div>}<section style={panel}><div style={{display:'flex',justifyContent:'space-between'}}><h2>Open Queue</h2><strong>{cases.length}</strong></div><div style={{display:'grid',gap:8}}>{cases.map(c=><button key={c.id} onClick={()=>setSelected(c)} style={{...button,textAlign:'left',borderColor:selected?.id===c.id?'#8b5cf6':'#303342'}}><strong>{c.case_number} · {c.subject}</strong><small style={{display:'block',marginTop:4,color:'#a1a1aa'}}>{c.specialist_type||c.support_type} · {c.priority} · {c.status}{c.next_response_due_at?` · due ${new Date(c.next_response_due_at).toLocaleString()}`:''}{c.appointment_requested?' · appointment requested':''}</small></button>)}</div></section>{selected&&<section style={panel}><h2>{selected.case_number}</h2><div style={grid}><label>Priority<select value={selected.priority} onChange={e=>{setSelected({...selected,priority:e.target.value});update({priority:e.target.value});}} style={input}><option>urgent</option><option>high</option><option>normal</option><option>low</option></select></label><label>Specialist<select value={selected.specialist_type||'general_artist_support'} onChange={e=>{setSelected({...selected,specialist_type:e.target.value});update({specialistType:e.target.value});}} style={input}>{specialists.map(x=><option key={x}>{x}</option>)}</select></label><label>Escalation<select value={selected.escalation_level||0} onChange={e=>{const n=Number(e.target.value);setSelected({...selected,escalation_level:n});update({escalationLevel:n});}} style={input}>{[0,1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Assignee<input value={selected.assigned_to||''} onChange={e=>setSelected({...selected,assigned_to:e.target.value})} onBlur={e=>update({assignedTo:e.target.value})} style={input}/></label></div><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Reply to artist…" style={{...input,minHeight:120,marginTop:12}}/><button disabled={busy||!reply.trim()} onClick={send} style={{...primary,marginTop:8}}>Send Staff Reply</button><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button onClick={()=>update({status:'in_progress'})} style={button}>In Progress</button><button onClick={()=>update({status:'waiting_on_user'})} style={button}>Waiting on User</button><button onClick={()=>update({status:'closed',resolutionSummary:'Resolved by Pie Support'})} style={button}>Close Case</button></div></section>}</div></main>}
const panel:React.CSSProperties={padding:18,borderRadius:18,background:'#11131b',border:'1px solid #292c39'};const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10};const input:React.CSSProperties={width:'100%',padding:11,borderRadius:10,border:'1px solid #343746',background:'#090a10',color:'#fff'};const button:React.CSSProperties={padding:'10px 12px',borderRadius:10,border:'1px solid #343746',background:'#151722',color:'#fff'};const primary:React.CSSProperties={padding:'12px 16px',border:0,borderRadius:10,background:'#7c3aed',color:'#fff',fontWeight:900};
